services:
  postgres:
    image: postgres:18
    container_name: ledger-postgres
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: