name: Set up Gradle Java project
description: Sets up Java 21, Gradle, and Gradle wrapper permissions

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '21'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle wrapper executable
      shell: bash
      run: chmod +x ./gradlew